version: '3.8'
networks:
  metric:
    external: True
    name: metric-all
volumes:
  prometheus:
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=2d'
    networks:
      - metric
    volumes:
      - /mnt/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus
    logging:
      options:
        tag: "admin"

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    deploy:
      mode: global
    command: -logtostderr -docker_only
    # ports:
    #   - 8080:8080
    networks:
      - metric
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock,ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    logging:
      options:
        tag: "admin"

  node-exporter:
    image: prom/node-exporter:latest
    deploy:
      mode: global
    # ports:
    #   - 9100:9100
    networks:
      - metric
    volumes:
      - /:/rootfs:ro
    logging:
      options:
        tag: "admin"

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - metric
    volumes:
      - grafana/datasources:/etc/grafana/provisioning/datasources/
      - grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - grafana/dashboards:/etc/grafana/dashboards/
      - grafana/grafana.ini:/etc/grafana/grafana.ini
      - tls:/etc/grafana/tls/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
    logging:
      options:
        tag: "admin"
